### ISSUE TITLE
TextStyle

### ISSUE THREAD

**Issue by enzobonggio** [ltdangkhoa/Flutter-Animation-Progress-Bar#4]
you cant modify in any way how the text is displayed. Adding textStyle as a param or maybe leave it as a Widget where you could enter anything you want

**Comment by Hesamedin** [comment]
I also need to change the color of the text value. In dark mode the color of my progress is white and the text value is invisible.

**Comment by ltdangkhoa** [comment]
Solved with 1.0.6
Thanks for your feedbacks
