### ISSUE TITLE
Version at https://pub.dev/packages/flutter_animation_progress_bar is not latest

### ISSUE THREAD

**Issue by jlubeck** [ltdangkhoa/Flutter-Animation-Progress-Bar#6]
Looks like the version that gets installed doesn't include https://github.com/ltdangkhoa/Flutter-Animation-Progress-Bar/pull/2

**Comment by jlubeck** [comment]
By the way, that commit break the widget
It's missing the declaration of the 2 new variables

  final Color borderColor;
  final double borderWidth;

**Comment by ltdangkhoa** [comment]
@jlubeck Sorry for late response. I've commit the latest with your suggest as well as publish package to pub.dev
