### ISSUE TITLE
Library for android

### ISSUE THREAD

**Issue by hasinaarmanj** [ltdangkhoa/Flutter-Animation-Progress-Bar#8]
Hi dear can you create this library for android studio.

Please

**Comment by ltdangkhoa** [comment]
> Hi dear can you create this library for android studio.
> 
> Please

Hi,

This lib is currently publish on pub.dev as Flutter package. What do you mean about Android Studio

**Comment by hasinaarmanj** [comment]
I want to use it in java android studio native apps

**Comment by hasinaarmanj** [comment]
Ok dear but how can I use it on android studio native apps java. I really love this progressbar but can't use it without flutter. And I dont know flutter.
If you made a library for android studio project it will be so fine.

**Comment by ltdangkhoa** [comment]
> Ok dear but how can I use it on android studio native apps java. I really love this progressbar but can't use it without flutter. And I dont know flutter.
> If you made a library for android studio project it will be so fine.

This package is available only for Flutter (Dart). Why don't you give Flutter a try? ;)

**Comment by hasinaarmanj** [comment]
I installed flutter but I don't understand it layout and many more.
If you make it for native android studio project it will be so fine.

Please dear do it. I search for a week I dont find any best library like
yours.


Thanks

**Comment by hasinaarmanj** [comment]
I will check you profile evry day for that library
